Louis branch 1
lacattano/DevOps-Course-Starter pull request #1
Opened 2022-08-02 14:32 UTC by lacattano

Please make sure you are raising this PR against your own repository and not the original. If it says https://github.com/CorndelWithSoftwire in the search bar right now, you are in the wrong place!

Please also don't forget to submit the PR's url to Aptem afterwards (by clicking on the corresponding exercise component, pasting the url in the textbox that appears and then pressing the finish button).

2022-08-02 16:01 UTC, Jonesey13 requested changes
OK looks mostly there. This would pass an M1 project ex review but there are issues that prevent it passing M2 and M3 project ex reviews:
M2: `requests` missing as a dependency, details on how to provide the environment variables are incomplete (needs to be listed in the .env.template file as well)
M3: Missing an `.env.test` file

More details/suggestions are provided in the review comments below...

2022-08-02 16:01 UTC, Jonesey13 commented on todo_app/app.py
> +import requests
You are using the requests python dependency yet it is not listed in your `pyproject.toml` file and so this dependency will not be installed on developers' machines when running `poetry install`.

To fix this you should run `poetry add requests` from a terminal.

2022-08-02 16:01 UTC, Jonesey13 commented on todo_app/data/trello_items.py
> +    url = f'https://api.trello.com/1/boards/{os.getenv("TRELLO_BOARD_ID")}/lists'
These new Trello environment variables should also be mentioned in the `.env.template` file. You do mention this in the `README.md` but the exact variable names are not stated.

2022-08-02 16:01 UTC, Jonesey13 commented on todo_app/app.py
> +    @app.route('/update_status', methods=['POST'])
Inconsistent casing used on HTTP method: `Post` vs `POST`

2022-08-02 16:01 UTC, Jonesey13 commented on todo_app/data/trello_items.py
> +        "key":os.getenv("API_KEY"),
(Minor Style Issue) Probably want a space after the semicolon here (a little crammed atm)

2022-08-02 16:01 UTC, Jonesey13 commented on todo_app/data/trello_items.py
> +    response = requests.request("POST", url, params=querystring)
If you're assigning the response to a variable here you should probably do something with the variable (e.g. check the response was successful via `response.raise_for_status()`)

2022-08-02 16:01 UTC, Jonesey13 commented on test_app.py
> +
Unnecessary newline

2022-08-02 16:01 UTC, Jonesey13 commented on test_get_items.py
> +    test_todo_items = get_items.todo_items
`#Act` needs a newline before it (to clearly mark out the Arrange/Act/Assert sections)

2022-08-02 16:01 UTC, Jonesey13 commented on test_get_items.py
> +    test_todo_items = get_items.todo_items
Also the `#Assert` section isn't declared anywhere

2022-08-02 16:01 UTC, Jonesey13 commented on test_app.py
> +    file_path = find_dotenv('.env.test')
There is no `.env.test` file, i.e. this test likely works with real credentials.

2022-08-03 08:13 UTC, lacattano commented
LV= Classification: Internal

Thanks for the quick feedback Alex I’ll update and submit it as m2 evidence.

From: Alex Jones ***@***.***>
Sent: 02 August 2022 17:02
To: lacattano/DevOps-Course-Starter ***@***.***>
Cc: Cattano, Louis ***@***.***>; Author ***@***.***>
Subject: Re: [lacattano/DevOps-Course-Starter] Louis branch 1 (PR #1)

ATTENTION: External email - This message has been sent from outside LV=.

@Jonesey13 requested changes on this pull request.

OK looks mostly there. This would pass an M1 project ex review but there are issues that prevent it passing M2 and M3 project ex reviews:
M2: requests missing as a dependency, details on how to provide the environment variables are incomplete (needs to be listed in the .env.template file as well)
M3: Missing an .env.test file

More details/suggestions are provided in the review comments below...

________________________________

In todo_app/app.py<https://github.com/lacattano/DevOps-Course-Starter/pull/1#discussion_r935750592>:

>  from todo_app.flask_config import Config

+import requests

You are using the requests python dependency yet it is not listed in your pyproject.toml file and so this dependency will not be installed on developers' machines when running poetry install.

To fix this you should run poetry add requests from a terminal.

________________________________

In todo_app/data/trello_items.py<https://github.com/lacattano/DevOps-Course-Starter/pull/1#discussion_r935752105>:

> @@ -0,0 +1,41 @@

+from flask import Flask, render_template, request

+

+import requests

+import os

+

+def get_trello_cards():

+    url = f'https://api.trello.com/1/boards/{os.getenv("TRELLO_BOARD_ID")}/lists'

These new Trello environment variables should also be mentioned in the .env.template file. You do mention this in the README.md but the exact variable names are not stated.

________________________________

In todo_app/app.py<https://github.com/lacattano/DevOps-Course-Starter/pull/1#discussion_r935761154>:

> +    @app.route('/create-todo', methods=['Post'])

+    def create_new_todo():

+        response = trello_items.create_todo()

+        return index()

+

+    @app.route('/update_status', methods=['POST'])

Inconsistent casing used on HTTP method: Post vs POST

________________________________

In todo_app/data/trello_items.py<https://github.com/lacattano/DevOps-Course-Starter/pull/1#discussion_r935763226>:

> @@ -0,0 +1,41 @@

+from flask import Flask, render_template, request

+

+import requests

+import os

+

+def get_trello_cards():

+    url = f'https://api.trello.com/1/boards/{os.getenv("TRELLO_BOARD_ID")}/lists'

+

+    print(os.getenv("API_KEY"))

+

+    querystring = {

+        "key":os.getenv("API_KEY"),

(Minor Style Issue) Probably want a space after the semicolon here (a little crammed atm)

________________________________

In todo_app/data/trello_items.py<https://github.com/lacattano/DevOps-Course-Starter/pull/1#discussion_r935764803>:

> +    }

+

+    response = requests.get(url, params=querystring)

+    response_json = response.json()

+    return response_json

+

+def create_todo():

+    url = "https://api.trello.com/1/cards"

+    new_todo_title = request.form['todo-name']

+    querystring = {

+        "key":os.getenv("API_KEY"),

+        "token":os.getenv("API_TOKEN"),

+        "idList":os.getenv("TRELLO_TODO_LIST_ID"),

+        "name": new_todo_title

+    }

+    response = requests.request("POST", url, params=querystring)

If you're assigning the response to a variable here you should probably do something with the variable (e.g. check the response was successful via response.raise_for_status())

________________________________

In test_app.py<https://github.com/lacattano/DevOps-Course-Starter/pull/1#discussion_r935765631>:

> @@ -0,0 +1,39 @@

+import pytest, requests, os

+from dotenv import load_dotenv, find_dotenv

+from todo_app import app

+

***@***.***

+

+def client():

+    file_path = find_dotenv('.env.test')

+    load_dotenv(file_path, override=True)

+    test_app = app.create_app()

+    with test_app.test_client() as client:

+

Unnecessary newline

________________________________

In test_get_items.py<https://github.com/lacattano/DevOps-Course-Starter/pull/1#discussion_r935766724>:

> +    #Act

+    test_todo_items = get_items.todo_items

#Act needs a newline before it (to clearly mark out the Arrange/Act/Assert sections)

________________________________

In test_app.py<https://github.com/lacattano/DevOps-Course-Starter/pull/1#discussion_r935769023>:

> @@ -0,0 +1,39 @@

+import pytest, requests, os

+from dotenv import load_dotenv, find_dotenv

+from todo_app import app

+

***@***.***

+

+def client():

+    file_path = find_dotenv('.env.test')

There is no .env.test file, i.e. this test likely works with real credentials.

________________________________

In test_get_items.py<https://github.com/lacattano/DevOps-Course-Starter/pull/1#discussion_r935767392>:

> +    #Act

+    test_todo_items = get_items.todo_items

Also the #Assert section isn't declared anywhere

—
Reply to this email directly, view it on GitHub<https://github.com/lacattano/DevOps-Course-Starter/pull/1#pullrequestreview-1058997005>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AWRHE7ENR32KNQG77YSYILDVXFA6JANCNFSM55LMR7CQ>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

This email (including any attachment) may contain confidential and/ or legally privileged information. If you are not the intended recipient, please advise the sender immediately and destroy it and any copies. Unauthorised access, use, disclosure, storage or copying of this email is not permitted and, unless you are the intended recipient, you are not entitled to rely on it in any way. Any opinions expressed in this email are those of the individual sending it and not necessarily those of LV=.

This email is believed to be free of any virus or other defect. However, communication by email cannot be guaranteed to be free from defect, error free or secure. If you choose to communicate with us by email you must realise that there can be no guarantee of privacy and you should carry out your own security checks before opening any email or attachment. LV= accepts no liability for any loss or damage which may be caused by any lack of privacy, software viruses or other defect.

LV= reserves the right to monitor and inspect any email (including any attachment) sent to and/or from LV= for reasons of security and for monitoring internal compliance with our office policies. LV= may use email monitoring or blocking software at its discretion. You are responsible for ensuring that any email you send is appropriate and within the bounds of the law.

LV= and Liverpool Victoria are trade marks of Liverpool Victoria Financial Services Limited and LV= and Liverpool Victoria are trading styles of the Liverpool Victoria group of companies. Liverpool Victoria General Insurance Group Limited (LVGIG) is part of the Allianz Group. The registered office address for all LVGIG companies is 57 Ladymead, Guildford, Surrey, GU1 1DB. Information about the LV= group of companies can be found via this link 'www.lv.com/insurance/terms/lv-companies<http://www.lv.com/insurance/terms/lv-companies/>'.

2022-08-24 09:00 UTC, JackMead commented
Changes since the previous review here reviewed on https://github.com/lacattano/DevOps-Course-Starter/pull/2, but basically feel free to merge this when you're ready!

2022-09-14 10:15 UTC, merged